import EStyleSheet from 'react-native-extended-stylesheet';

EStyleSheet.build({
  $textColor: '#0275d8',
  $primaryFontFamily: 'RobotoCondensed-Regular',
  $secondaryFontFamily: 'Oswald-Regular',
  $blue: '#0484FC',
  $lightViolet: '#ab6fe3',
  $violet: '#933ae9',
  $violetOpacity: 'rgba(147,58,233,0.38)',
  $transparentGray: 'rgba(16,16,16,0.63)',
  $white: '#ffffff',
  $primaryColor: '#111115',
  $black: '#000000',
  $secondaryColor: '#1dec92',
  $tertiaryColor: '#F5F5F5',
  $borderGray: '#979797',
  $gray: '#C0C0C0',
  $textViolet: '#8E09E9',
  $grayText: '#2D1F1F6C',
  $darkGray: 'rgba(0,0,0,0.38)',
  $deepDarkGray: 'rgba(0,0,0,0.58)',
  $lightGray: '#C8C7C9',
  $mint: '#1BE58D',
  $lightBlue: '#77E9CD',
  $lightGreen: '#33E27A',
  $darkViolet: '#2A0941',
  $backgroundGray: '#E4E4E9',
  $secondTextGrey: '#9595B7',
  $grey: '#F4F4F4',
  $scarlet: '#C22001',
  $red: '#D0021B',
  $mainTextColor: '#0f144a',
  $spaceBase: '5%',
  $inputBorderRadius: 4,
  $errorColor: '#F86969',
  $headerBackgroundColor: '#EEEEF3',
  $fontSmallSize: 12,
  $fontMediumSize: 14,
  $fontBigSize: 16,
  $letterSpacing: 0.3,
  $H1Size: 32,
  $H2Size: 26,
  $H2_5Size: 22,
  $H3Size: 18,
  $boldFontFamily: 'RobotoCondensed-Bold',
  $activitiesTitle: 'RobotoCondensed-Regular',
  $activitiesMain: 'Oswald-Regular',
});

export default function buildTheme() {
  return {
    colors: {
      white: EStyleSheet.value('$white'),
      primary: EStyleSheet.value('$white'),
      secondary: EStyleSheet.value('$secondaryColor'),
      darkGray: EStyleSheet.value('$darkGray'),
      lightGray: EStyleSheet.value('$lightGray'),
      borderGray: EStyleSheet.value('$borderGray'),
      accent: EStyleSheet.value('$secondaryColor'),
      black: EStyleSheet.value('$black'),
      error: EStyleSheet.value('$errorColor'),
      placeholder: EStyleSheet.value('$darkGray'),
      background: EStyleSheet.value('$white'),
    },
    fonts: {
      regular: 'RobotoCondensed-Regular',
      medium: 'RobotoCondensed-Bold',
      thin: 'RobotoCondensed-Regular',
      light: 'RobotoCondensed-Regular',
      activitiesMain: 'RobotoCondensed-Regular',
      activitiesTitle: 'Oswald-Regular',
    },
    styles: {
      container: {
        flexGrow: 1,
        paddingHorizontal: '5%',
        paddingTop: 20,
        paddingBottom: 30,
      },
      arrowBtn: {
        width: 7,
        height: 14,
      },
    },
    text: {
      large: {
        fontFamily: EStyleSheet.value('$primaryFontFamily'),
        fontWeight: '600',
        fontStyle: 'normal',
        fontSize: 20,
        letterSpacing: 0.25,
        lineHeight: 24,
      },
      title: {
        fontFamily: EStyleSheet.value('$primaryFontFamily'),
        fontWeight: '600',
        fontSize: 16,
        letterSpacing: 0.5,
      },
      medium: {
        fontFamily: EStyleSheet.value('$primaryFontFamily'),
        fontSize: 14,
        letterSpacing: 0.25,
        lineHeight: 20,
      },
      small: {
        fontFamily: EStyleSheet.value('$primaryFontFamily'),
        fontSize: 12,
        letterSpacing: 0.4,
        lineHeight: 14,
      },
      link: {
        fontFamily: EStyleSheet.value('$primaryFontFamily'),
        fontWeight: '600',
        fontSize: 12,
        textDecorationLine: 'underline',
        letterSpacing: 0.21,
        lineHeight: 20,
      },
    },
    picker: {
      inputIOS: {
        paddingLeft: 12,
        paddingRight: 20,
        height: 56,
        width: '100%',
        lineHeight: 20,
        fontFamily: EStyleSheet.value('$primaryFontFamily'),
        fontSize: 16,
        fontWeight: 'normal',
        letterSpacing: 0.15,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: EStyleSheet.value('$lightGray'),
      },
      placeholder: {
        color: EStyleSheet.value('$darkGray'),
        fontFamily: EStyleSheet.value('$primaryFontFamily'),
        fontSize: 16,
      },
      iconContainer: {
        position: 'absolute',
        right: 8,
        top: 15,
      },
      fontFamily: EStyleSheet.value('$primaryFontFamily'),
    },
  };
}
